### ISSUE TITLE
Spinner when providing one user

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/dev-time-cli#10]
Should we show an elegant spinner when providing only one user? Didn't do it at first to be able to pipe it to another function.

**Comment by sindresorhus** [comment]
I don't really see the point. `dev-time` is fast:

```
❯ time dev-time SamVerschueren
23:15 - 12 Dec. 2015

real	1.12s
```

**Comment by SamVerschueren** [comment]
Thanks, just wanted more opinions on this one :). Can always reconsider if someone comes up with a valid reason to do it.
