### ISSUE TITLE
FR: `--json` for parseable output.

### ISSUE THREAD

**Issue by hemanth** [SamVerschueren/dev-time-cli#7]
Ok usecase: Lets say we have a webpage that lists all the members of an github org, will their current time ;) [Wired usecase, this is the first thing that came to my mind]

**Comment by SamVerschueren** [comment]
They should use [dev-time](https://github.com/SamVerschueren/dev-time) directly instead of `dev-time-cli`.

**Comment by hemanth** [comment]
Agree.
